services:

  librarymanagement:
    image: microservices/librarymanagement:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      - 5005:5005
    env_file:
      - "library.env"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: